{"uuid": "33644e3a-de4e-4830-b851-96006aba1868", "children": ["a473a356-8efc-4b40-91ad-301a0e2e6632"], "befores": [{"name": "configuration", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: <html>\r\n<head><title>401 Authorization Required</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>401 Authorization Required</h1></center>\r\n<hr><center>nginx/1.14.2</center>\r\n</body>\r\n</html>\r\n\n\n", "trace": "  File \"C:\\Users\\Admin\\Desktop\\hw_12_python-master\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\Admin\\Desktop\\hw_12_python-master\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\Admin\\Desktop\\hw_12_python-master\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Admin\\Desktop\\hw_12_python-master\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Admin\\Desktop\\hw_12_python-master\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 877, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Admin\\Desktop\\hw_12_python-master\\tests\\conftest.py\", line 33, in configuration\n    driver = webdriver.Remote(\n             ^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Admin\\Desktop\\hw_12_python-master\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 208, in __init__\n    self.start_session(capabilities)\n  File \"C:\\Users\\Admin\\Desktop\\hw_12_python-master\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 292, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Admin\\Desktop\\hw_12_python-master\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Admin\\Desktop\\hw_12_python-master\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 193, in check_response\n    raise exception_class(value)\n"}, "start": 1714901757127, "stop": 1714901757854}], "start": 1714901757127, "stop": 1714901757990}