{"uuid": "93dc8807-51b6-4bca-8f0e-7bcf2b1cd6fe", "children": ["4f5bc3d4-784a-4653-8e2e-b34991599735"], "befores": [{"name": "configuration", "status": "broken", "statusDetails": {"message": "NameError: name 'os' is not defined. Did you forget to import 'os'\n", "trace": "  File \"C:\\Users\\Admin\\Desktop\\hw_12_python-master\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\Admin\\Desktop\\hw_12_python-master\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\Admin\\Desktop\\hw_12_python-master\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Admin\\Desktop\\hw_12_python-master\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Admin\\Desktop\\hw_12_python-master\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 877, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Admin\\Desktop\\hw_12_python-master\\tests\\conftest.py\", line 25, in configuration\n    login = os.getenv('LOGIN')\n            ^^\n"}, "start": 1714905251944, "stop": 1714905251944}], "start": 1714905251944, "stop": 1714905252010}